[target.xtensa-esp32-none-elf]
# --connect-under-reset is required because Embassy puts the device in sleep mode, which prevents JTAG connection.
# For this reason, --preverify will not work.
runner = "probe-rs run --chip=esp32 --always-print-stacktrace --connect-under-reset"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tdefmt.x",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]

[server]
port = 50000
address = "127.0.0.1"
